### ISSUE TITLE
Spam prevention measures

### ISSUE THREAD

**Issue by 153** [lily-mayfield/bubblebbs#29]
Posts to reject as spam 

Coming in:

- [x] post from bad IP (individual address or wildcard ban) 
- [x] CAPTCHA not completed (if board is public; on by default) 
- [ ] Dummy "spamtrap" textbox had text entered 

Processing: 
- [x] post is identical to prior post (likely a user error, or a very low IQ spammer) 
- [ ] bad name / tripcode (add poster to badip list)
- [x] bad text in comment body (wordfilter should be regex), add poster to badip list 

These are all cases that should automatically reject a post

**Comment by lily-mayfield** [comment]
I should make post messages a unique column in the SQL.

(just a note for myself)

**Comment by lily-mayfield** [comment]
Related: #27

**Comment by lily-fyi** [comment]
@ACE-Recliner captcha only works with javascript.

**Comment by lily-mayfield** [comment]
recaptcha finished

**Comment by lily-mayfield** [comment]
Closing. Please see: #72 and #71
