### ISSUE TITLE
custom css support/css style switcher

### ISSUE THREAD

**Issue by ACE-Recliner** [lily-mayfield/bubblebbs#33]
like on minichan.  todo

**Comment by lily-fyi** [comment]
I don't see the custom css stuff on minichan, can you point this out?

**Comment by lily-fyi** [comment]
Oh no wait I see. It literally just replaces the other style... ok... I usually use some extension for this back in the day but I can definitely add this without pain! It'd be v v v easy but I'd also have to start using cookies... it's been eons since ive done cookies tbqh

**Comment by ACE-Recliner** [comment]
for reference (on minichan), you change styles thru the settings dashboard, as seen here http://minichan.org/dashboard

**Comment by lily-mayfield** [comment]
@ACE-Recliner finished.
