### ISSUE TITLE
add lispmark 

### ISSUE THREAD

**Issue by 153** [lily-mayfield/bubblebbs#58]
**Is your feature request related to a problem? Please describe.**
No problem, but consider adding a limited dialect of LispMark to the engine to compliment MarkDown / other markup dialects. Make it "safe" by restricting the initial tag pool and by escaping all input. 

**Describe the solution you'd like**
shitty but open source [Lispmark parser](https://github.com/153/lispmark/blob/master/parse.py) by me 

**Describe alternatives you've considered**
Sexpcode [is a thing](https://github.com/Cairnarvon/sexpcode) but Lispmark is simply better. 

**Additional context**
If you make Textile a  supported markup language you will be executed.

**Comment by lily-fyi** [comment]
What's the advantages over our current markdown generator?
