### ISSUE TITLE
css styling boxes

### ISSUE THREAD

**Issue by MaiKawakami** [lily-mayfield/bubblebbs#6]
The current issues with the board is if you use custom CSS , it can become difficult to read text if it goes over an image that is in the css style. A certain way to fix this is to to make sure all posts are contained within a box (i.e. 4chan) that overlays the css design. 

![image](https://user-images.githubusercontent.com/38994064/39657280-6f292232-4fd4-11e8-8141-14f582502ad2.png)
![image](https://user-images.githubusercontent.com/38994064/39657282-7643ff2e-4fd4-11e8-81a3-6aab6e2afc80.png)

Also, there should be a limit to how long something in the box should be otherwise it'll break the page.

**Comment by lily-mayfield** [comment]
What is the custom CSS are you using? So basically I should model my HTML around 4chan's and such so that custom CSS works nicely with it? I might be able to acocmplish this withotu sacrificing the minicahn-like layout I have and am fond of.

**Comment by ACE-Recliner** [comment]
I think he just means that message boxes etc should be opaque, so that the background doesn't overlap with them (like in the 2nd image).  Also to be a bit pedantic, that style is ripped from Tohno-chan, not 4chan.

**Comment by MrEthical** [comment]
Minichan also has boxes 
![image](https://user-images.githubusercontent.com/38994064/39657361-1d0cfcde-4fd5-11e8-96d1-d6a81d67b42d.png)

**Comment by lily-mayfield** [comment]
@MaiKawakami @ACE-Recliner I closed out #33
